Feat: Console Output Builder
tempestphp/tempest-framework pull request #232
Opened 2024-04-03 18:34 UTC by przemyslaw-przylucki

Hiya - first extracted PR out of #228 

Includes console output builder implementation and replaces commands to use the builder instead

2024-04-04 04:07 UTC, brendt requested changes
Great PR! Splitting it into smaller parts does indeed help me wrap my head around things :D 

The only major question I have is about the container, would love your input on that!

2024-04-04 04:07 UTC, brendt commented on src/Console/ConsoleOutputBuilder.php
> +    public function write(ConsoleOutput $to): self
And like I said in a previous comment: I wonder if we can pass in the Console via the initializer, and get rid of this write method altogether? Maybe it's not as trivial as I think it is. Let me know your thoughts

2024-04-04 04:07 UTC, brendt commented on src/Console/ConsoleOutputBuilder.php
> +    public function toString(bool $format = true): string
Why would `format` be toggleable?

2024-04-04 04:07 UTC, brendt commented on src/Console/RenderConsoleCommandOverviewMessage.php
> +                fn (ConsoleOutputBuilder $builder) => $builder->error(' Discovery cache is enabled! ')->blank()
Should probably be a warning instead of an error

2024-04-04 04:07 UTC, brendt commented on src/Console/RenderConsoleCommandOverviewMessage.php
> +            $builder->formatted(ConsoleStyle::BOLD(ConsoleStyle::BG_BLUE(' ' . ucfirst($group) . ' ')));
Why don't we provide a method for this style? I'm ok if it changes a bit, I just put random something together initially.

2024-04-04 18:45 UTC, przemyslaw-przylucki commented on src/Console/ConsoleOutputBuilder.php
> +    public function toString(bool $format = true): string
Lemme know what you wanna do here!

2024-04-04 18:48 UTC, przemyslaw-przylucki commented
@brendt I've pushed some stuff, lemme know what you think now - I like the current solution quite a lot 😎

2024-04-05 06:06 UTC, brendt requested changes

2024-04-05 06:06 UTC, brendt commented on src/Console/Commands/RoutesCommand.php
> +        $this->builder
Consistent naming: $this->outputBuilder

2024-04-05 06:07 UTC, brendt commented
> I like the current solution quite a lot

Same! I'll take care of that inconsistent naming issue, and merge this!

2024-04-05 06:07 UTC, merged

2024-04-05 06:51 UTC, brendt commented
Hi @przemyslaw-przylucki 

Some important things to mention about this PR. I'm in the process of extracting all console-related code into a separate package that's used by the framework. The reason being that I want `tempest/console` to work as a standalone package.

This impacts your work in two ways:

- All subsequent PRs regarding console should be sent to https://github.com/tempestphp/tempest-console
- In porting your ConsoleOutputBuilder to this package, I wondered: why not add these methods on the `ConsoleOutput` itself? Did you consider that?