feat: add autowire/autodiscovery of interfaces to classes
tempestphp/tempest-framework pull request #501
Opened 2024-09-28 20:20 UTC by Jeroen-G

## Rationale
First of all, it is exciting to play with this new framework! I like a lot of it already, but I hit one snag when building some services. I usually have an interface for them (for example to make mocking easier). But with Tempest it looks like this would require a initializer class. And I am too lazy to make those for all my services 😜 
A while ago I made an Autowire implementation for Laravel ([link](https://github.com/Jeroen-G/autowire/)) so I thought I would start porting that a little bit to Tempest. So this first PR adds the Autowire attribute which allows autodiscovery of classes.

Let me know what you think!

## How to use it
GreetingController:
```php
final readonly class GreetingController
{
    public function __construct(public GreetingInterface $service)
    {}

    #[Get('/greetings')]
    public function index(): View
    {
        return view('greeting.view.php')->data(greeting: $this->service->greeting());
    }
}
```
GreetingInterface:
```php
interface GreetingInterface
{
    public function greeting(): string;
}
```
GreetingService:
```php
use Tempest\Container\Autowire;

#[Autowire]
final class GreetingService implements GreetingInterface
{
    public function greeting(): string
    {
        return 'hello world';
    }
}
```

2024-09-28 21:18 UTC, Jeroen-G commented on src/Tempest/Container/src/AutoDiscovery.php
> +        $this->container->setDefinitions(unserialize($payload));
Maybe the container should merge the definitions, or have a separate collection for the autowired stuff.

2024-09-29 04:54 UTC, brendt commented
Oooh, I like this! I'll probably review the PR tomorrow, but I'm pretty confident I'll merge it :)

2024-09-29 11:26 UTC, yassiNebeL commented
> Oooh, I like this! I'll probably review the PR tomorrow, but I'm pretty confident I'll merge it :)

I appreciate your contribution! However, Tempest already has a Singleton attribute that handles service injection directly into the container. Could you clarify how this autowiring feature complements or improves upon that, and whether it addresses scenarios where the existing attribute falls short?

2024-09-29 12:03 UTC, Jeroen-G commented
> > Oooh, I like this! I'll probably review the PR tomorrow, but I'm pretty confident I'll merge it :)
> 
> I appreciate your contribution @Jeroen-G! However, Tempest already has a Singleton attribute that handles service injection directly into the container. Could you clarify how this autowiring feature complements or improves upon that, and whether it addresses scenarios where the existing attribute falls short?

Did you try out the example in the PR description? That is something the Singleton attribute cannot do. Automatically wiring interfaces to implementation is different from registering a singleton implementation. So that is where this feature complements upon :)

2024-09-29 12:46 UTC, yassiNebeL commented
> > > Oooh, I like this! I'll probably review the PR tomorrow, but I'm pretty confident I'll merge it :)
> 
> > 
> 
> > I appreciate your contribution @Jeroen-G! However, Tempest already has a Singleton attribute that handles service injection directly into the container. Could you clarify how this autowiring feature complements or improves upon that, and whether it addresses scenarios where the existing attribute falls short?
> 
> 
> 
> Did you try out the example in the PR description? That is something the Singleton attribute cannot do. Automatically wiring interfaces to implementation is different from registering a singleton implementation. So that is where this feature complements upon :)

Thank you for the clarification, I see the distinction now! The automatic wiring of interfaces to implementations definitely complements the existing functionality.

To further improve and standardize this feature, what do you think about introducing a handle method? It could help centralize and streamline the autowiring process, making it more consistent across different implementations.

Wdyt?

2024-09-29 14:29 UTC, Jeroen-G commented
Could you give a code example?

2024-09-29 15:04 UTC, yassiNebeL commented
Thank you for your quick response! I believe it might be helpful to explore the idea conceptually first.

Introducing a handler method or class could help centralize the autowiring logic, making it easier to manage and reuse across multiple services. This approach could allow us to standardize the process without getting too focused on individual service implementations. It’s more about making a design choice that simplifies invocation and enhances flexibility in the long run.

This version maintains a respectful and collaborative tone, while also expressing your point clearly. Let me know if you’d like to refine it further!

2024-09-30 10:05 UTC, shaffe-fr commented
This PR allows to tell the container: when I want a GreetingInterface give me this implementation.

2024-09-30 10:06 UTC, brendt requested changes
This is great! 

I've got one idea though I wanted to pitch though, but I'm not sure I like it myself. 

I don't really like too many attributes on a class. I was wondering if it would make sense if we combined the autowiring attribute and singleton attribute into one, something like:

```php
#[Singleton(for: Interface::class)]
```

I don't think it's better than this, but I wanted to pitch the idea just in case.

2024-09-30 18:43 UTC, Jeroen-G commented on src/Tempest/Container/src/AutoDiscovery.php
> +        $this->container->setDefinitions(unserialize($payload));
Ok! 👍

2024-09-30 18:48 UTC, Jeroen-G commented on src/Tempest/Container/src/AutoDiscovery.php
> +            $this->container->register($interface, fn (Container $container) => $container->get($class->getName()));
Fixed!

2024-09-30 18:48 UTC, Jeroen-G commented on src/Tempest/Container/src/AutoDiscovery.php
> +final class AutoDiscovery implements Discovery
Fixed!

2024-10-01 04:12 UTC, brendt commented
I actually think just making the combination of both attributes `#[Autowire]` and `#[Singleton]` will be the best approach, as it causes the least confusion, and prevents one thing from being done in two ways. 

Not sure yet how I feel about `#[Configure]`, but let's open a new discussion for it :)

Btw: are you on Discord?

2024-10-01 04:13 UTC, brendt commented
I think we're ready to merge? Can you rebase the branch on main?

2024-10-01 08:48 UTC, brendt approved these changes

2024-10-01 08:48 UTC, merged

2024-10-01 08:48 UTC, brendt commented
Super nice! I'll write some docs for this as well :)

2024-10-01 10:28 UTC, Jeroen-G commented
Cool! Thanks, and I see you already found my discord handle :)