feat(support): Improve array helper with additional methods
tempestphp/tempest-framework pull request #557
Opened 2024-10-08 19:34 UTC by gturpin-dev

As discussed in #543 This pull request add some additional methods to the array helper.

As seen in other PR/Issues the goal for this helper isn't to be a clone of laravel collections but a much simpler wrapper around native php's array functions and some other useful methods such as mapWithKeys, pluck etc..

Here's my current work progression :
- [x] put()
- [x] combine()
- [x] keys()
- [x] dump()
- [x] diff()
- [x] diffKeys()
- [x] merge()
- [x] intersect()
- [x] intersectKeys()
- [x] unique()
- [x] flip()
- [x] pad()
- [x] add()
- [x] push()
- [ ] reduce()
- [ ] pluck()
- [ ] chunk() ?
- [ ] random()
- [ ] pull() ?
- [ ] search() ?
- [ ] slice()
- [ ] sort() => and probably its variations
- [ ] flatten() => I must check if unwrap isn't doing the same before
- [ ] wrap() ?

If i'm doing something wrong please tell me 🙏

2024-10-09 04:43 UTC, brendt requested changes

2024-10-09 04:43 UTC, brendt commented on src/Tempest/Support/src/ArrayHelper.php
> +        dump($this->array, ...$dumps); // @phpstan-ignore-line
You should use `lw` instead of `dump` here, `lw` integrates with Tempest's logger as well: https://tempestphp.com/docs/framework/logging/

2024-10-09 04:43 UTC, brendt commented on src/Tempest/Support/src/ArrayHelper.php
>          dd($this->array, ...$dd); // @phpstan-ignore-line
Could you change this `dd` call to `ld` while you're working on it? 😁

2024-10-09 04:44 UTC, brendt commented
Super nice! Maybe we should already merge these functions and have a new PR for the others? I prefer to have small and quick PRs over huge ones that might become stale over time.

Random question: would you like to write the docs for ArrayHelper as well? Definitely not a requirement, but I figured I'd ask just in case :)

2024-10-09 17:18 UTC, brendt commented
> All yours, I can then move the TODO to the issue and make a PR for each new method

No need for it to be a PR per method btw :) Maybe we just merge this one, and then you make one more? 

Docs PR indeed goes into https://github.com/tempestphp/tempest-docs You're free to make a new page (just add a markdown file in https://github.com/tempestphp/tempest-docs/tree/main/app/Front/Docs/Content)

2024-10-09 17:19 UTC, brendt commented
If you make those two changes, I'm happy to merge this :)

2024-10-09 19:20 UTC, gturpin-dev commented
I'm ok, then it will be 2 PRs 👍

Thanks

I'm gonna fix this ASAP 🙏

2024-10-10 13:06 UTC, gturpin-dev commented
Those two functions `dump` and `dd` seems to already be aliased to `lw/ld` but maybe the `symfony/var-dumper` goes first and this is ignored.

Anyways I changed the declarations as requested.

2024-10-11 08:52 UTC, brendt commented
> symfony/var-dumper

Yeah that's the problem indeed…

2024-10-11 08:52 UTC, brendt approved these changes

2024-10-11 08:52 UTC, brendt commented
Anyway, this looks good to merge! Awesome PR :)

2024-10-11 08:56 UTC, merged

2024-10-11 08:59 UTC, gturpin-dev commented
> FYI the failing codestyle check can be fixed by running `composer qa` locally. I've done it for you now, thought I'd let you know for future PRs :)

Interesting, I see it in the contributing guidelines but having error with it and don't know why. 
Any ideas ? @brendt 

![screenshort2024-10-11_105842](https://github.com/user-attachments/assets/84570fed-abb4-4b93-bbfd-858b826ac469)

2024-10-11 09:01 UTC, brendt commented
Huh, no idea 🤔 @aidan-casey do you know?

2024-10-11 11:10 UTC, aidan-casey commented
It's a permissions issue - either on the file or the user to run shell scripts.

Are you running this from Docker by chance?

Side note: I think Composer QA will fail on Windows machines, so I should look at that.

2024-10-11 11:45 UTC, gturpin-dev commented
Hmm I'm working on windows on WSL 2, maybe it's related then.

And no docker here.

If you want to test some things on windows you can open an issue and tag me if you want !

For now I run the tools manually and it do the work.