feat: add isList() and isAssoc() methods in ArrayHelper for array type checking
tempestphp/tempest-framework pull request #566
Opened 2024-10-11 13:55 UTC by yassiNebeL

2024-10-11 14:25 UTC, innocenzi requested changes

2024-10-11 14:25 UTC, innocenzi commented on src/Tempest/Support/src/ArrayHelper.php
> +    public function isList()
```suggestion
     */
    public function isList(): bool
```

2024-10-11 14:25 UTC, innocenzi commented on src/Tempest/Support/src/ArrayHelper.php
> +    public function isAssoc()
```suggestion
     */
    public function isAssoc(): bool
```

2024-10-11 18:00 UTC, innocenzi commented on src/Tempest/Support/src/ArrayHelper.php
> +    public function isAssoc()
Please remove the docblock return type as well :)

2024-10-12 04:51 UTC, merged

2024-10-12 04:51 UTC, brendt commented
Thanks!