[bug] fix duplicate command completion
tempestphp/tempest-framework pull request #600
Opened 2024-10-19 12:48 UTC by Treggats

fixes #411

Worked on this with @Bapawe 

This PR removes duplicate completions for commands

**Steps to reproduce**
Like mentioned in the issue run
```shell
php tempest di
```
Expected output
```shell
~/P/tempest-framework ❯❯❯ php tempest di
 Command di not found 
 Did you mean to run one of these? 
[x] fail
[ ] discovery:status
[ ] discovery:clear
[ ] tail
Press enter to confirm, ctrl+c to cancel
```

2024-10-19 12:58 UTC, Treggats commented on src/Tempest/Console/src/Testing/ConsoleTester.php
> +    public function getContent(?callable $callback = null): array
helper to get the output for the console

2024-10-19 12:58 UTC, Treggats commented on src/Tempest/Console/src/Middleware/ResolveOrRescueMiddleware.php
> +            if (in_array($consoleCommand->getName(), $similarCommands, strict: true)) {
if the command name is already is in the list, then don't add it again

2024-10-19 12:58 UTC, Treggats commented on tests/Integration/Console/Middleware/ResolveOrRescueMiddlewareTest.php
> +    public function it_does_not_duplicate_completed_commands(): void
similar to the previous test, but this test more the inner workings

2024-10-20 04:38 UTC, brendt requested changes

2024-10-20 04:38 UTC, brendt commented on tests/Integration/Console/Middleware/ResolveOrRescueMiddlewareTest.php
> +            ->getContent(fn (array $buffer) => $formatOutput(array_pop($buffer)));
Maybe better to call this `getOutput`?

2024-10-20 04:39 UTC, brendt commented
Looks good! Take a look at my one comment and rebase on main, after that this is good to merge

2024-10-20 10:37 UTC, Treggats commented on tests/Integration/Console/Middleware/ResolveOrRescueMiddlewareTest.php
> +            ->getBuffer(fn (array $buffer) => $formatOutput(array_pop($buffer)));
I think that `getBuffer()` aptly describes the output it returns

2024-10-22 07:57 UTC, brendt approved these changes

2024-10-22 07:59 UTC, merged

2024-10-22 07:59 UTC, brendt commented
Thanks!