feat: add json data type (#547)
tempestphp/tempest-framework pull request #709
Opened 2024-11-09 08:42 UTC by MrYamous

Part of #547 to add the `json` data type to the table statements

Latest versions of MySQL accept default value for `json` but this require a version check.
I didn't want to add this complexity (at least for this pr) as this was not done either for `text` type before

2024-11-09 12:11 UTC, brendt commented
> Do you think we should check if value provided as default is a valid json ? json_validate seems free to use as Tempest require 8.3+

Yes, that makes sense!

> Latest versions of MySQL accept default value for json but this require a version check.
> I didn't want to add this complexity (at least for this pr) as this was not done either for text type before

Yeah we can ignore this for now :)

We should also make sure that JSON columns are eventually mapped to array properties. But that's outside the scope of this PR.

2024-11-09 12:13 UTC, brendt requested changes

2024-11-09 12:13 UTC, brendt commented on src/Tempest/Database/src/QueryStatements/CreateTableStatement.php
> +        ?string $default = null
Let's use validate_json 👍

2024-11-09 13:45 UTC, MrYamous commented
`json_validate` added :) 
I'm not sure about the Exception name and the new test, let me know if this is suitable

2024-11-12 12:26 UTC, brendt approved these changes

2024-11-12 12:28 UTC, merged

2024-11-12 12:28 UTC, brendt commented
Thanks!