fix(router): Just fixing some minor casing issues in HTTP 418
tempestphp/tempest-framework pull request #823
Opened 2024-12-06 21:54 UTC by blackshadev

Fixes https://github.com/tempestphp/tempest-framework/issues/778 .

Somebody has to fix the most important and widely used HTTP statuscodes out there. 

For anybody who doesn't know, [418 is a official HTTP status code](https://www.rfc-editor.org/rfc/rfc2324#section-2.3.2) introduces as an RFC during april fools  by the official networking working committee at that time. I don't know why and how, but it was accepted and it stuck. Recently there was a movement to remove it, but surprise surprise , after more than 10 years not only did people use it. People loved this small easter egg in a rigid spec of the foundation of our internet. 

[Read the RFC](https://www.rfc-editor.org/rfc/rfc2324) if you have the time, it is a proper laugh.

2024-12-06 23:30 UTC, innocenzi requested changes

2024-12-06 23:30 UTC, innocenzi commented on src/Tempest/Http/src/Status.php
> +            418 => "I'm a Teapot",
```suggestion
            418 => "I'm a teapot",
```

Please be a little serious. The specs say "I'm a teapot", not "I'm a Teapot".

2024-12-06 23:32 UTC, innocenzi commented on src/Tempest/Http/tests/StatusTest.php
> +            [418, "I'm a Teapot"],
```suggestion
            [418, "I'm a teapot"],
```

2024-12-06 23:38 UTC, innocenzi approved these changes

2024-12-06 23:38 UTC, merged

2024-12-07 03:15 UTC, aidan-casey commented
Thank you, @blackshadev! This was driving me nuts and I'm awarding this the "Perfect Storm" label for adding context. ;)