normalized text files and use LF line endings
tempestphp/tempest-framework pull request #828
Opened 2024-12-09 16:37 UTC by kevinfrom

Fixes #826 

Normalizes text file and ensures LF file endings, preventing line-errors on Windows (and WSL) env.

2024-12-09 23:35 UTC, innocenzi commented
Looks like this breaks tests 😅

2024-12-10 03:33 UTC, ericsizemore requested changes
I would recommend removing `text=auto` and leaving it as just `* text eol=lf`

2024-12-15 18:46 UTC, innocenzi commented
Have you tried `* text eol=lf` @kevinfrom?

2025-01-19 02:33 UTC, closed without merging

2025-01-25 02:15 UTC, xHeaven commented
@kevinfrom could you check if this issue happens on [this branch](https://github.com/xHeaven/tempest-framework/tree/patch-1)? I don't have a Windows system right now.

2025-02-12 17:34 UTC, kevinfrom commented
@xHeaven Well it fixes some problems, but many remain. I've tried to run `composer run-script qa` and modifying the `qa` script as is fails. See my test output here attached.

[qa.txt](https://github.com/user-attachments/files/18771849/qa.txt)

[qa-dont-validate-packages.txt](https://github.com/user-attachments/files/18771850/qa-dont-validate-packages.txt)

[qa-dont-validate-packages-and-clear-discovery-cache.txt](https://github.com/user-attachments/files/18771851/qa-dont-validate-packages-and-clear-discovery-cache.txt)