feat(console): add `make:migration` command
tempestphp/tempest-framework pull request #871
Opened 2024-12-23 15:41 UTC by gturpin-dev

This PR adds the `make:migration` command
This checks a TODO on #759 

The command allows you to create a raw migration file in SQL with the following command :  
`tempest make:migration create-book-table raw`

You can create a classic migration file in PHP using :  
`tempest make:migration CreateBookTable`

Or you can even create a migration file for a specific existing model with :  
`tempest make:migration CreateBookTable model`
Tempest will scan the main namespace and let you chose in all classes that implements `DatabaseModel`  the Model you want to create the migration for  
The final generated file and statements are then slightly differents

2024-12-23 15:43 UTC, gturpin-dev commented
Note that this PR should not be merged without fixing #866  and #867 as those issues have been discovered while working on this PR.

2025-03-26 04:35 UTC, brendt commented
@gturpin-dev do I remember correct that this PR is blocked because of missing property hooks support in nette/generator? I haven't looked into the detail yet, but I assume that's because of `$name` property? You can actually write it without property hooks: `$name = 'dummy-name'`. Would be solve the issue?

2025-03-26 07:57 UTC, gturpin-dev commented
@brendt 
> do I remember correct that this PR is blocked because of missing property hooks support in nette/generator?

Absolutely

> I haven't looked into the detail yet, but I assume that's because of $name property? You can actually write it without an explicit property hook: public $name = 'dummy-name'. Would be solve the issue?

I don't remember which thing in particular but it's actually a property hook in the stub  
So yes, if you prefer we can move this to an old declaration for now

2025-03-26 13:48 UTC, brendt commented
Let's do the old declaration and get this merged 😁

2025-03-28 13:38 UTC, gturpin-dev commented
@brendt Some tests aren't related to my changes

But some tests seems to fail because the raw sql migration stub are discovered I guess
Do you know how to avoid it ?

2025-03-28 13:42 UTC, innocenzi commented
@gturpin-dev you might want to update discovery to ignore stub files: https://github.com/tempestphp/tempest-framework/blob/main/src/Tempest/Database/src/MigrationDiscovery.php#L38

2025-03-28 14:04 UTC, gturpin-dev commented
@innocenzi I think this is good for me  
Is the CI broken on #main ?

2025-03-28 17:18 UTC, brendt commented
@innocenzi is this because of the pathhelper changes?

2025-03-28 18:14 UTC, innocenzi requested changes

2025-03-28 18:14 UTC, innocenzi commented on tests/Integration/Database/Commands/MakeMigrationCommandTest.php
> +use Tempest\Core\ComposerNamespace;
This has changed to `Tempest\Support\Namespace\Psr4Namespace`

2025-03-28 18:15 UTC, innocenzi commented
> @innocenzi is this because of the pathhelper changes?

Yes it is!

2025-04-02 11:58 UTC, brendt commented
Hey @gturpin-dev just checking, would you like some help to finish this PR? I'm happy to make the changes but if you still planned to do them that's fine as well :)

2025-04-08 06:50 UTC, merged

2025-04-08 06:50 UTC, brendt commented
Let's merge! Thanks @gturpin-dev

2025-04-17 10:03 UTC, gturpin-dev commented
Thanks for help 🙏